# Generated by Django 5.0.6 on 2024-05-14 05:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('owner_id', models.CharField(blank=True, max_length=128, null=True)),
                ('code', models.CharField(default=core.models.gen_promo, max_length=32, unique=True)),
            ],
        ),
    ]
